import React, { useState } from 'react';
import { TrendingUp, Info, ChevronDown, ChevronUp } from 'lucide-react';
import { useForecast, useRenewableForecast } from '@/hooks';
import { Card, CardHeader } from '@/components/ui/Card';
import { Tabs, Badge, Skeleton, DataRow } from '@/components/ui';
import { ForecastChart, RenewableChart } from '@/charts';
import { formatMW } from '@/utils/calculations';
import { aiModelInfo } from '@/mock/aiData';
import { format } from 'date-fns';
import type { ForecastConfidence } from '@/types';

function ConfidencePill({ confidence }: { confidence: ForecastConfidence }) {
  const colorMap = { HIGH: 'success', MEDIUM: 'warning', LOW: 'danger' } as const;
  const labelMap = { HIGH: 'High Confidence', MEDIUM: 'Medium Confidence', LOW: 'Low Confidence' };
  return <Badge variant={colorMap[confidence]} size="sm">{labelMap[confidence]}</Badge>;
}

export default function ForecastPage() {
  const [horizon, setHorizon] = useState<'1h' | '6h' | '24h' | '7d'>('24h');
  const { data: forecast, loading } = useForecast(horizon);
  const { data: renewForecast } = useRenewableForecast();
  const [showModelDetails, setShowModelDetails] = useState(false);

  const horizonTabs = [
    { id: '1h', label: '1 Hour' },
    { id: '6h', label: '6 Hours' },
    { id: '24h', label: '24 Hours' },
    { id: '7d', label: '7 Days' },
  ];

  const horizonLabel: Record<string, string> = {
    '1h': 'next hour',
    '6h': 'next 6 hours',
    '24h': 'next 24 hours',
    '7d': 'next 7 days',
  };

  return (
    <div className="p-5 space-y-5 max-w-[1400px]">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-lg font-bold text-slate-100">AI Energy Forecast</h1>
          <p className="text-xs text-slate-500 mt-0.5">Predicted energy demand and generation for the {horizonLabel[horizon]}</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="warning" size="sm">SIMULATED FORECAST</Badge>
          <Tabs
            tabs={horizonTabs}
            active={horizon}
            onChange={(id) => setHorizon(id as typeof horizon)}
          />
        </div>
      </div>

      {/* Simple AI summary banner */}
      <div className="flex items-start gap-3 bg-blue-500/8 border border-blue-500/20 rounded-xl px-4 py-3">
        <Info size={15} className="text-blue-400 shrink-0 mt-0.5" aria-hidden="true" />
        <div className="flex-1">
          <p className="text-xs text-slate-300 leading-relaxed">
            <span className="text-blue-400 font-semibold">AI Energy Forecast: </span>
            This forecast is generated by our AI model using simulated station data. It predicts energy demand, generation, and battery state for the selected time period. Always verify against current conditions before acting.
          </p>
          {/* Collapsible model details */}
          <button
            onClick={() => setShowModelDetails(!showModelDetails)}
            className="flex items-center gap-1 text-[11px] text-cyan-500 hover:text-cyan-400 mt-1.5 transition-colors"
            aria-expanded={showModelDetails}
          >
            {showModelDetails ? 'Hide' : 'Show'} model details
            {showModelDetails ? <ChevronUp size={11} /> : <ChevronDown size={11} />}
          </button>
          {showModelDetails && (
            <div className="flex items-center gap-4 text-xs flex-wrap mt-2 pt-2 border-t border-slate-800/50">
              <span className="text-slate-500">Model: <span className="text-slate-300 font-medium">{aiModelInfo.name} v{aiModelInfo.version}</span></span>
              <span className="text-slate-600">|</span>
              <span className="text-slate-500">Trained: <span className="text-slate-300 font-medium">{format(new Date(aiModelInfo.lastTrained), 'dd MMM yyyy')}</span></span>
              <span className="text-slate-600">|</span>
              <span className="text-slate-500">Data coverage: <span className="text-slate-300 font-medium">{aiModelInfo.dataCoveragedays} days</span></span>
              <span className="text-slate-600">|</span>
              <span className="text-slate-500">7-day accuracy: <span className="text-emerald-400 font-medium">{aiModelInfo.accuracy7d}%</span></span>
            </div>
          )}
        </div>
      </div>

      {/* 4 Key Summary Cards */}
      {loading ? (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-20 rounded-xl" />)}
        </div>
      ) : forecast ? (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { label: 'Expected Peak Demand', value: formatMW(forecast.predictedPeakLoad), note: 'Highest load expected in period' },
            { label: 'Average Demand', value: formatMW(forecast.predictedAvgLoad), note: 'Typical consumption over period' },
            { label: 'Battery at End of Period', value: `${forecast.predictedEndSOC.toFixed(1)}%`, note: 'Predicted battery level' },
            { label: 'Risk of Energy Shortage', value: `${forecast.shortageProbability}%`, note: forecast.shortageProbability < 10 ? 'Low risk' : forecast.shortageProbability < 30 ? 'Moderate risk' : 'High risk — action needed' },
          ].map((item, i) => (
            <div key={i} className="bg-[#041219] border border-slate-800/60 rounded-xl p-4">
              <p className="text-xs text-slate-500">{item.label}</p>
              <p className="text-2xl font-bold font-mono text-slate-100 mt-1">{item.value}</p>
              <p className="text-[11px] text-slate-600 mt-0.5">{item.note}</p>
            </div>
          ))}
        </div>
      ) : null}

      {/* Forecast Chart */}
      <Card>
        <CardHeader
          title={`Energy Demand Forecast — Next ${horizon}`}
          subtitle="Predicted load with confidence range"
          icon={<TrendingUp size={15} />}
          actions={forecast && <ConfidencePill confidence={forecast.overallConfidence} />}
        />
        <div className="mb-3 flex items-center gap-4 text-xs">
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-0.5 bg-cyan-400 inline-block rounded" />
            <span className="text-slate-500">Actual</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-0.5 bg-amber-400 inline-block rounded border-dashed" style={{ borderTop: '1px dashed' }} />
            <span className="text-slate-500">Forecast</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-2 bg-amber-400/10 inline-block rounded border border-amber-400/20" />
            <span className="text-slate-500">Confidence range</span>
          </div>
        </div>
        {loading ? <Skeleton className="h-72 rounded-xl" /> : forecast ? (
          <ForecastChart data={forecast.dataPoints} unit="MW" height={300} showConfidenceBands />
        ) : null}
      </Card>

      {/* Renewable Forecast */}
      {renewForecast && (
        <Card>
          <CardHeader
            title="Renewable Generation Forecast"
            subtitle="Solar and wind output over the next 24 hours"
            icon={<TrendingUp size={15} />}
          />
          {/* @ts-ignore */}
          <RenewableChart data={renewForecast} height={220} />
        </Card>
      )}

      {/* Advanced breakdown (collapsible) */}
      {forecast && (
        <div className="border border-slate-800/60 rounded-xl overflow-hidden">
          <div className="px-4 py-3 bg-slate-900/30">
            <p className="text-[10px] font-semibold text-slate-600 uppercase tracking-wider">Detailed Forecast Breakdown</p>
          </div>
          <div className="p-4 grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <p className="text-xs font-semibold text-slate-500 mb-2">Load Forecast</p>
              <div className="space-y-0">
                <DataRow label="Peak load" value={formatMW(forecast.predictedPeakLoad)} />
                <DataRow label="Min load" value={formatMW(forecast.predictedMinLoad)} />
                <DataRow label="Average load" value={formatMW(forecast.predictedAvgLoad)} />
                <DataRow label="Shortage probability" value={`${forecast.shortageProbability}%`} />
              </div>
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-500 mb-2">Generation Forecast</p>
              <div className="space-y-0">
                <DataRow label="Avg renewable" value={formatMW(forecast.predictedRenewable)} />
                <DataRow label="Generator runtime" value={`${forecast.predictedGeneratorRuntime}h`} />
                <DataRow label="Fuel consumption" value={`${forecast.predictedFuelConsumption.toFixed(0)} L`} />
              </div>
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-500 mb-2">Model Information</p>
              <div className="space-y-0">
                <DataRow label="Predicted end SOC" value={`${forecast.predictedEndSOC.toFixed(1)}%`} />
                <DataRow label="Overall confidence" value={forecast.overallConfidence} mono={false} />
                <DataRow label="Model version" value={forecast.modelVersion} mono={false} />
                <DataRow label="Generated at" value={format(new Date(forecast.generatedAt), 'HH:mm dd/MM')} />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
